//Auths
const LOGIN_LOADING = 'LOGIN_LOADING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';

const ROOM_DETAILS_LOADING = 'ROOM_DETAILS_LOADING';
const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL';
