export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

//Rooms
export const GET_ROOMS_LOADING = 'GET_ROOMS_LOADING';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILED = 'GET_ROOMS_FAILED';

export const GET_DETAILS_ROOMS_LOADING = 'GET_DETAILS__ROOMS_LOADING';
export const GET_DETAILS_ROOMS_SUCCESS = 'GET_DETAILS_ROOMS_SUCCESS';
export const GET_DETAILS_ROOMS_FAILED = 'GET_DETAILS_ROOMS_FAILED';

export const GET_ROOMS_BY_ID_BUILDING_LOADING =
  'GET_ROOMS_BY_ID_BUILDING_LOADING';
export const GET_ROOMS_BY_ID_BUILDING_SUCCESS =
  'GET_ROOMS_BY_ID_BUILDING_SUCCESS';
export const GET_ROOMS_BY_ID_BUILDING_FAILED =
  'GET_ROOMS_BY_ID_BUILDING_FAILED';

export const GET_SINGLE_ROOM_LOADING = 'GET_SINGLE_ROOM_LOADING';
export const GET_SINGLE_ROOM_SUCCESS = 'GET_SINGLE_ROOM_SUCCESS';
export const GET_SINGLE_ROOM_FAILED = 'GET_SINGLE_ROOM_FAILED';

export const UPDATE_ROOM_LOADING = 'UPDATE_ROOM_LOADING';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_ROOM_FAILED = 'UPDATE_ROOM_FAILED';

export const CREATE_ROOM_BY_ID_BUILDING_LOADING =
  'CREATE_ROOM_BY_ID_BUILDING_LOADING';
export const CREATE_ROOM_BY_ID_BUILDING_SUCCESS =
  'CREATE_ROOM_BY_ID_BUILDING_SUCCESS';
export const CREATE_ROOM_BY_ID_BUILDING_FAILED =
  'CREATE_ROOM_BY_ID_BUILDING_FAILED';

export const DELETE_ROOM_BY_ID_LOADING = 'DELETE_ROOM_BY_ID_LOADING';
export const DELETE_ROOM_BY_ID_SUCCESS = 'DELETE_ROOM_BY_ID_SUCCESS';
export const DELETE_ROOM_BY_ID_FAILED = 'DELETE_ROOM_BY_ID_FAILED';

export const GET_FACILITIES_LOADING = 'GET_FACILITIES_LOADING';
export const GET_FACILITIES_SUCCESS = 'GET_FACILITIES_SUCCESS';
export const GET_FACILITIES_FAILED = 'GET_FACILITIES_FAILED';

export const GET_BFACILITIES_LOADING = 'GET_BROKEN_FACILITIES_LOADING';
export const GET_BFACILITIES_SUCCESS = 'GET_BROKEN_FACILITIES_SUCCESS';
export const GET_BFACILITIES_FAILED = 'GET_BROKEN_FACILITIES_FAILED';

//Buildings
export const GET_BUILDINGS_LOADING = 'GET_BUILDINGS_LOADING';
export const GET_BUILDINGS_SUCCESS = 'GET_BUILDINGS_SUCCESS';
export const GET_BUILDINGS_FAILED = 'GET_BUILDINGS_FAILED';

export const GET_DATA_BUILDINGS_ID_LOADING = 'GET_DATA_BUILDINGS_ID_LOADING';
export const GET_DATA_BUILDINGS_ID_SUCCESS = 'GET_DATA_BUILDINGS_ID_SUCCESS';
export const GET_DATA_BUILDINGS_ID_FAILED = 'GET_DATA_BUILDINGS_ID_FAILED';

export const CREATE_BUILDING_LOADING = 'CREATE_BUILDING_LOADING';
export const CREATE_BUILDING_SUCCESS = 'CREATE_BUILDING_SUCCESS';
export const CREATE_BUILDING_FAILED = 'CREATE_BUILDING_FAILED';

export const EDIT_BUILDING_LOADING = 'EDIT_BUILDING_LOADING';
export const EDIT_BUILDING_SUCCESS = 'EDIT_BUILDING_SUCCESS';
export const EDIT_BUILDING_FAILED = 'EDIT_BUILDING_FAILED';

export const DELETE_BUILDING_LOADING = 'DELETE_BUILDING_LOADING';
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS';
export const DELETE_BUILDING_FAILED = 'DELETE_BUILDING_FAILED';

//User
export const GET_USER_INFO_LOADING = 'GET_USER_INFO_LOADING';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';

export const GET_NMFACILITIES_LOADING =
  'GET_NEEDED_MAINTAINING_FACILITIES_LOADING';
export const GET_NEEDED_MAINTAINING_FACILITIES_SUCCESS =
  'GET_NEEDED_MAINTAINING_FACILITIES_SUCCESS';
export const GET_NEEDED_MAINTAINING_FACILITIES_FAILED =
  'GET_NEEDED_MAINTAINING_FACILITIES_FAILED';

export const GET_MFACILITIES_LOADING = 'GET_MAINTAINING_FACILITIES_LOADING';
export const GET_MFACILITIES_SUCCESS = 'GET_MAINTAINING_FACILITIES_SUCCESS';
export const GET_MFACILITIES_FAILED = 'GET_MAINTAINING_FACILITIES_FAILED';

//Facilities

export const DELETE_FACILITY_LOADING = 'DELETE_FACILITY_LOADING';
export const DELETE_FACILITY_SUCCESS = 'DELETE_FACILITY_SUCCESS';
export const DELETE_FACILITY_FAILED = 'DELETE_FACILITY_FAILED';

export const CREATE_FACILITY_LOADING = 'CREATE_FACILITY_LOADING';
export const CREATE_FACILITY_SUCCESS = 'CREATE_FACILITY_SUCCESS';
export const CREATE_FACILITY_FAILED = 'CREATE_FACILITY_FAILED';

export const GET_FACILITY_LOADING = 'GET_FACILITY_LOADING';
export const GET_FACILITY_SUCCESS = 'GET_FACILITY_SUCCESS';
export const GET_FACILITY_FAILED = 'GET_FACILITY_FAILED';

export const EDIT_FACILITY_LOADING = 'EDIT_FACILITY_LOADING';
export const EDIT_FACILITY_SUCCESS = 'EDIT_FACILITY_SUCCESS';
export const EDIT_FACILITY_FAILED = 'EDIT_FACILITY_FAILED';

//Categories

export const GET_CATEGORIES_LOADING = 'GET_CATEGORIES_LOADING';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

//Status
export const GET_STATUS_LOADING = 'GET_STATUS_LOADING';
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAILED = 'GET_STATUS_FAILED';
